Feat/communication firewall
iotaledger/stronghold.rs pull request #158
Opened 2021-03-04 00:23 UTC by elenaf9

# Description of change

Integrate the firewall into the communication actor, instead of expecting the user to provide a firewall actor.
Add procedural macro derive to generate permission for a Request  and create unit variant of the request, e.g.:
```
pub enum Request {
    VariantA { inner : u32 },
    VariantB(String),
    VariantC
}
```
will generate 

```
impl ToPermissionVariants<RequestPermission> for Request {
    fn to_permission_variants(&self) -> RequestPermission {
        match self {
            Request::VariantA {inner: _} => RequestPermission::VariantA,
            Request::VariantB(_) => RequestPermission::VariantB,
            Request::VariantC=> RequestPermission::VariantC,
        }
    }
}

impl VariantPermission for Request {

    fn variant_permission_value(&self) -> PermissionSum {
        self.to_permission_variants().variant_permission_value()
    }

    fn is_permitted(&self, permission: PermissionSum) -> bool {
        self.to_permission_variants().is_permitted(permission)
    }
}

#[derive(Clone, Debug)]
pub enum RequestPermission {
   VariantA,
   VariantB,
}

impl VariantPermission for RequestPermission {

  fn variant_permission_value(&self) -> PermissionSum {
    match self {
      VariantA => 0,
      VariantB => 1,
      VariantC => 2
    }
  }

  fn is_permitted(&self, permission: PermissionSum) -> bool {
     (permission >> self.variant_permission_value()) & 1 != 0
  }
}

```

This allows setting different permissions for each request variant (similar to how read/write/execute permissions in linux work).
The firewall takes a sum (e.g. 5) and check with that if a request is allowed (in this case VariantA and VariantC would be, Variant B not).

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Existing firewall tests, and new tests for the permission concept.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-10 08:24 UTC, nothingismagick requested changes
I really like this approach and don't have any problems with it. I think it will be important to document the default behaviour of the Firewall, which is to allow any outgoing connection, but deny any incoming.

I would also like to see a README in the `communication-macros` folder.

2021-03-11 18:16 UTC, tensor-programming requested changes
Looks good to go.

2021-03-11 18:16 UTC, tensor-programming commented on client/src/interface.rs
> +            self.communication_actor.as_ref().unwrap(),
Wonder if any of these unwraps can be removed.

2021-03-11 18:16 UTC, tensor-programming commented on communication/communication-macros/src/lib.rs
> +        panic!("More then 32 variants on enums are not allowed.");
I wonder if this should be here or if it should be a recoverable error.

2021-03-11 18:16 UTC, tensor-programming approved these changes

2021-03-11 21:14 UTC, nothingismagick approved these changes

2021-03-11 21:14 UTC, merged