Docs/improve seo
iotaledger/stronghold.rs pull request #256
Opened 2021-09-07 07:28 UTC by lucas-tortora

# Description of change

* Changed file locations to match urls
* Browser friendly, descriptive urls
* Added keywords, image and description meta tags
* Removed slugs

## Links to any relevant issues

* Resolves  iotaledger/docs.iota.org#36

## Type of change

- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Documentation Fix

## How the change has been tested

Docs site was built and served locally using node 12.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2021-09-07 11:34 UTC, nothingismagick approved these changes
Thanks!

2021-09-15 06:55 UTC, lucas-tortora commented
@iotaledger/tech-writers , could someone review this ?

2021-09-15 21:18 UTC, aleksei-korolev requested changes

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +description: Contribute to Stronghold by joining the IOTA Stronghold Initiative, contributing to the GitHub repository and documentation, or sharing your knowledge on Discord.
Contribute by contributing

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/retrospective.md
> +description: This document will detail the development of the Stronghold Engine library for IOTA's Stronghold project, touching upon different revisions and the lessons that were learnt from them.
```suggestion
description: History behind the development of the Stronghold Engine library that reflects upon previous revisions and the lessons learnt.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/retrospective.md
> +- crate
```suggestion
- development
- history
- crate
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/specs/engineering.md
> +description: This document introduces the High-Level Specification of the Stronghold.
```suggestion
description: This document introduces the high-level specification of Stronghold.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/specs/overview.md
> +description: This section contains a description of the scope of the project, and working documents that detail the engineering and requirements specifications.
```suggestion
description: This section describes the scope of the project and includes working documents on engineering and requirements specifications.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/structure/derive.md
> +description: The Structure:Derive crate contains procedural macros for Stronghold.
```suggestion
description: The Derive crate contains procedural macros for Stronghold.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/structure/engine/store.md
> +description: Store contains a key:value cache for the Stronghold Engine.
```suggestion
description: Store contains a key-value cache for the Stronghold Engine.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/structure/overview.md
> +description: In this section we describe the individual crates and components of Stronghold
```suggestion
description: In this section we describe individual crates and components of Stronghold.
```

2021-09-15 21:18 UTC, aleksei-korolev commented on documentation/docs/structure/utils.md
> +description: The Structure:utils crate contains common utilities for the stronghold libraries.
```suggestion
description: The Utils crate contains common utilities for the stronghold libraries.
```

2021-09-28 10:35 UTC, aleksei-korolev approved these changes

2021-09-28 11:26 UTC, merged