Support android target
iotaledger/stronghold.rs pull request #462
Opened 2022-11-14 13:22 UTC by samuel-rufi

# Description of change

This PR aims to fix the Android cross-compilation issue described in https://github.com/iotaledger/stronghold.rs/issues/460

## Type of change

- [X] Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Cross-compilation to Android works without compilation error.
Compiling to Linux/macOS runs continues to run fine.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-11-14 13:26 UTC, Thoralf-M commented on engine/runtime/src/memories/frag.rs
> +            .unwrap_or(Some(default_page_size.try_into().unwrap()))
Comment why it's safe to unwrap

2022-11-14 13:26 UTC, Thoralf-M requested changes
Changelog entry

2022-11-15 10:53 UTC, Thoralf-M approved these changes

2022-11-15 11:02 UTC, thibault-martinez approved these changes

2022-11-15 16:04 UTC, merged