Fix compilation for armv7-unknown-linux-gnueabihf target
iotaledger/stronghold.rs pull request #497
Opened 2023-10-06 12:07 UTC by Thoralf-M

# Description of change

Fix compilation for armv7-unknown-linux-gnueabihf target.
`nix::unistd::sysconf(nix::unistd::SysconfVar::PAGE_SIZE)` returns i32 instead of i64 there, that's why the conversion is needed.
Also applied two Clippy suggestions.

## Links to any relevant issues

https://github.com/iotaledger/iota-sdk/issues/1161

## Type of change

- [ ] Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo check --target armv7-unknown-linux-gnueabihf`

2023-10-30 12:54 UTC, thibault-martinez commented on engine/runtime/src/memories/frag.rs
> +            .unwrap_or(Some(default_page_size.try_into().unwrap()))
Are these unwraps really safe ? If yes please put a comment

2023-10-30 14:56 UTC, Thoralf-M commented on engine/runtime/src/memories/frag.rs
> +            .unwrap_or(Some(default_page_size.try_into().unwrap()))
Done

2024-03-06 10:02 UTC, semenov-vladyslav requested changes

2024-03-06 10:02 UTC, semenov-vladyslav commented on engine/runtime/src/memories/frag.rs
> +            .unwrap_or(Some(default_page_size.try_into().unwrap()))
`sysconf` returns `c_long`. Can't we just define `default_page_size` to be this type? Eg. `const DEFAULT_PAGE_SIZE: nix::libc::c_long = 0x1000;`? No need for a conversion, and the compiler will complain if the literal value doesn't fit `c_long` type.

2024-03-06 10:21 UTC, Thoralf-M commented on engine/runtime/src/memories/frag.rs
> +            .unwrap_or(Some(default_page_size.try_into().unwrap()))
Thanks for the suggestion, changed

2024-03-06 11:42 UTC, semenov-vladyslav approved these changes

2024-03-06 13:17 UTC, merged